DROP TABLE ID_GEN;
DROP TABLE UNS_EMAILLOG;
DROP TABLE UNS_SMSLOG;
DROP TABLE UNS_MSGLOG;
DROP TABLE UNS_FAILEDMSG;

CREATE TABLE ID_GEN(
SEQ_NAME VARCHAR(20) NOT NULL,
SEQ_COUNT BIGINT NOT NULL, 
PRIMARY KEY (SEQ_NAME)
);

CREATE TABLE UNS_EMAILLOG(
ID BIGINT NOT NULL, 
SYSID VARCHAR(20) NOT NULL,
EMAIL_ADDR VARCHAR(2000), 
EMAIL_CC VARCHAR(2000), 
EMAIL_BCC VARCHAR(2000), 
EMAIL_SUBJECT VARCHAR(4000) NOT NULL, 
EMAIL_BODY VARCHAR(4000) NOT NULL, 
EMAIL_AUX VARCHAR(2000),
SENSITIVE_IND CHAR(1),
EMAIL_DATETIME TIMESTAMP NOT NULL,
CREATED_DATETIME TIMESTAMP NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE UNS_SMSLOG(
ID BIGINT NOT NULL, 
SYSID VARCHAR(20) NOT NULL,
SMS_TELNO VARCHAR(2000) NOT NULL, 
SMS_BODY VARCHAR(2000) NOT NULL, 
SMS_AUX VARCHAR(2000),
SMS_DATETIME TIMESTAMP NOT NULL,
CREATED_DATETIME TIMESTAMP NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE UNS_MSGLOG(
ID BIGINT NOT NULL, 
SYSID VARCHAR(20) NOT NULL,
MSG_TYPE INTEGER NOT NULL, 
MSG_EMAIL VARCHAR(2000), 
MSG_EMAILCC VARCHAR(2000), 
MSG_EMAILBCC VARCHAR(2000),
MSG_TELNO VARCHAR(2000),
MSG_PERNR VARCHAR(50),
MSG_BODY VARCHAR(4000) NOT NULL, 
MSG_AUX VARCHAR(2000),
SENSITIVE_IND CHAR(1),
MSG_DATETIME TIMESTAMP NOT NULL,
CREATED_DATETIME TIMESTAMP NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE UNS_FAILEDMSG(
ID BIGINT NOT NULL, 
SYSID VARCHAR(20) NOT NULL,
MSG_TYPE INTEGER NOT NULL, 
MSG_EMAIL VARCHAR(2000), 
MSG_EMAILCC VARCHAR(2000), 
MSG_EMAILBCC VARCHAR(2000), 
MSG_TELNO VARCHAR(2000),
MSG_PERNR VARCHAR(50),
MSG_SUBJECT VARCHAR(4000) NOT NULL,
MSG_BODY VARCHAR(4000) NOT NULL, 
MSG_AUX VARCHAR(2000),
MSG_DATETIME TIMESTAMP NOT NULL,
FAILURE_TYPE INTEGER NOT NULL,
SENSITIVE_IND CHAR(1),
DEFUNCT_IND CHAR(1) NOT NULL DEFAULT 'N',
CREATED_DATETIME TIMESTAMP NOT NULL,
UPDATED_DATETIME TIMESTAMP NOT NULL,
PRIMARY KEY (ID)
);
